---
title: "Dengue Virus Distribution_Markdown Report"
output:
  html_document:
    df_print: paged
---

# 1.Prepare the RStudio Environment
```{r}
library(tidyverse)
combined_metadata <- as_tibble(read_tsv("/Users/yijunzhou/My Drive/Data Analysis_H2L2C/0813_github_repository/20230727_dengue_patient_metadata_combined.tsv"))
setwd("/Users/yijunzhou/My Drive/Data Analysis_H2L2C/0813_github_repository")
```

# 2.Look at "combined_metadata"
```{r}
names(combined_metadata)
head(combined_metadata)
```

# 3.Extract columns "Serotype" and "Location"
```{r}
sero_loc <- combined_metadata %>% select(Serotype, Location)
head(sero_loc)
```

# 4.Visualize "sero_loc"
```{r}
ggplot(sero_loc, aes(x = Location)) + geom_bar() 
ggplot(sero_loc, aes(x = Location, fill = Serotype)) + geom_bar() 
# x axis is too cramped, too many locations to plot

# how many distinct locations are there in the data frame?
sero_loc %>% distinct(Location)   #need to tidy-up the data

ggplot(sero_loc, aes(x = Serotype, fill = Serotype)) + geom_bar()
# shows the number counts for each serotype
```

# 5.Separate "Locations" into "Continent" and "Countries"
```{r}
sero_cont_count <- separate(sero_loc,"Location", into = c("Continents","Countries"), sep = "/") %>% 
  mutate(across(where(is.character), str_trim))  #remove the extra spaces in "Continents"and "Countries"
head(sero_cont_count)
```

# 6.  Visualizing Serotype vs Continents
```{r}
ggplot(sero_cont_count, aes(x = Continents, fill = Serotype)) + 
  geom_bar()   
```

# 7.  Visualizing Serotype vs Countries
```{r, fig.height = 8, fig.width = 20}
ggplot(sero_cont_count, aes(x = Countries, fill = Serotype)) + 
  geom_bar() + 
  theme (axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
```

# 8.  Serotype vs Countries + Legends
```{r, fig.height = 8, fig.width = 20}
ggplot(sero_cont_count, aes(x = Countries, fill = Serotype)) + 
  geom_bar() +              
  theme (axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  labs(title = "Number of Sequences Based on Serotypes and Countries") +
  ylab("Number of Reported Sequences") +
  xlab("Countries")
```
The x axis is very cramped. 

# 9. Serotype vs Countries vs Continents + Legends
```{r, fig.height = 10, fig.width = 20}
ggplot(sero_cont_count, aes(x = Countries, fill = Serotype), xaxt) + 
  geom_bar() +
  facet_wrap(~Continents, nrow = 2) +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
  labs(title = "Number of Sequences vs Serotypes vs Countries vs Continents") +
  ylab("Number of Reported Sequences") +
  xlab("Countries") +
  theme(strip.text.x = element_text(size = 10))
```
